# Etapa de construcción
FROM node:14 as build-step

WORKDIR /app

COPY package.json package-lock.json ./
RUN npm install

COPY . .
RUN npm run build -- --configuration production

# Etapa de producción
FROM nginx:alpine

COPY --from=build-step /app/dist/inventario-sole /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf

# Modificar la URL de la API
# RUN sed -i 's|http://localhost:5000|http://backend-service:5000|g' /usr/share/nginx/html/main*.js
# RUN sed -i "s|API_URL|$API_URL|g" /usr/share/nginx/html/main*.js
COPY entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh
EXPOSE 80

CMD ["/entrypoint.sh"]


# CMD ["nginx", "-g", "daemon off;"]

# docker build -t facundoguarnier/inventario-sole-frontend:v0.3 .