#! Etapa de construcción
FROM node:14 as build-step

WORKDIR /app

COPY package.json package-lock.json ./
RUN npm install

COPY . .
RUN npm run build -- --configuration production

#! Etapa de producción
FROM nginx:alpine

COPY --from=build-step /app/dist/inventario-sole /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf

COPY entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh
EXPOSE 80

CMD ["/entrypoint.sh"]


# docker build -t facundoguarnier/inventario-sole-frontend:v0.3 .