#T* ConfigMap
apiVersion: v1
kind: ConfigMap
metadata:
  name: flask-config

data:
  MONGO_URI: "mongodb://mongodb-service:37000/db-inventario-sole3.db"
  MONGO_DBNAME: "db-inventario-sole3.db"
  MONGO_COLLECTIONS: "usuarios,productos,movimientos,ventas,regalos,gift_cards,ultimasIDs"
  IMG_SIZE: "960,960"
  IMG_QUALITY: "70"

---
#T* Secret
apiVersion: v1
kind: Secret
metadata:
  name: flask-secrets
type: Opaque
stringData:
  SECRET_KEY: "MiClaveSuperSecretaQueNadieSabe12"
  JWT_SECRET_KEY: "OtraClaveSecretaQueNAdieSabe13"
  CONTRA_ADMIN: "admin123"
  CONTRA_BACKUP: "LaContraMasDificilDelMundo123"

---
#T* Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-backend
  template:
    metadata:
      labels:
        app: flask-backend
    spec:
      containers:
      - name: flask-backend
        image: facundoguarnier/inventario-sole-backend:v0.9
        resources:
          requests:
            cpu: "500m"
            memory: "512Mi"
          limits:
            cpu: "2500m"
            memory: "2048Mi"
        ports:
        - containerPort: 5000
        envFrom:
        - configMapRef:
            name: flask-config
        - secretRef:
            name: flask-secrets
        volumeMounts:
        - name: uploads
          mountPath: /app/uploads
      volumes:
      - name: uploads
        persistentVolumeClaim:
          claimName: uploads-pvc

---
#T* Service
apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  selector:
    app: flask-backend
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
      nodePort: 30050
  type: NodePort

---
#T* PersistentVolume
apiVersion: v1
kind: PersistentVolume
metadata:
  name: uploads-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: standard
  hostPath:
    path: "/path/to/uploads"

---
#T* PersistentVolumeClaim
#! Sin longhorn
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: uploads-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: standard

#! Con longhorn
# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: uploads-pvc
# spec:
#   accessModes:
#     - ReadWriteMany
#   resources:
#     requests:
#       storage: 10Gi
#   storageClassName: longhorn


#! docker build -t facundoguarnier/inventario-sole-backend:v0.4 .