apiVersion: apps/v1
kind: Deployment
metadata:
  name: angular-frontend
spec:
  replicas: 1  # Podemos reducir a 1 réplica si el tráfico es bajo
  selector:
    matchLabels:
      app: angular-frontend
  template:
    metadata:
      labels:
        app: angular-frontend
    spec:
      containers:
      - name: angular-frontend
        image: tuusuario/angular-frontend:v1
        ports:
        - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: angular-frontend-service
spec:
  selector:
    app: angular-frontend
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 80
  type: LoadBalancer

---

# apiVersion: networking.k8s.io/v1
# kind: Ingress
# metadata:
#   name: angular-frontend-ingress
#   annotations:
#     kubernetes.io/ingress.class: nginx
#     nginx.ingress.kubernetes.io/ssl-redirect: "false"
# spec:
#   rules:
#   - http:
#       paths:
#       - path: /
#         pathType: Prefix
#         backend:
#           service:
#             name: angular-frontend-service
#             port: 
#               number: 80

---

