apiVersion: apps/v1
kind: Deployment
metadata:
  name: angular-frontend
spec:
  replicas: 1  # Podemos reducir a 1 réplica si el tráfico es bajo
  selector:
    matchLabels:
      app: angular-frontend
  template:
    metadata:
      labels:
        app: angular-frontend
    spec:
      containers:
      - name: angular-frontend
        image: facundoguarnier/inventario-sole-frontend:v0.7
        ports:
        - containerPort: 80
        # env:
        # - name: API_URL
        #   value: "http://backend-service:5003"


# SI no funciona la conexion con el backend, uso la variable de entorno API_URL para los services en el frontend. 


---

apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  selector:
    app: angular-frontend
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 80
  type: LoadBalancer