#T* Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: angular-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: angular-frontend
  template:
    metadata:
      labels:
        app: angular-frontend
    spec:
      containers:
      - name: angular-frontend
        image: facundoguarnier/inventario-sole-frontend:v0.16
        resources:
          requests:
            cpu: "500m"
            memory: "512Mi"
          limits:
            cpu: "2500m"
            memory: "1536Mi"
        ports:
        - containerPort: 80
        env:
        - name: API_URL
          value: "http://backend-service:5000"

---
#T* Service
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  selector:
    app: angular-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30080
  type: NodePort


#! docker build -t facundoguarnier/inventario-sole-frontend:v0.11 .